### ISSUE TITLE
Calling GetAllOrdersAsync with multiply statuses

### ISSUE THREAD

**Issue by Muleskinner** [dougdellolio/coinbasepro-csharp#100]
It would be great if possible to call then GetAllOrdersAsync function with a list of statuses instead of just one.

**Comment by dougdellolio** [comment]
@Muleskinner this is already available just make sure you have the latest version. you can specify the `OrderStatus` when making this call. https://github.com/dougdellolio/gdax-csharp/blob/master/GDAXSharp/Services/Orders/Types/OrderStatus.cs#L8

**Comment by chrisw000** [comment]
Just to add on this... the GDAX docs says you can pass more than one status in.... so you might want (say) Rejected & Settled (only) in one call.

I think this is could be what @Muleskinner  means here? 

Currently you'd need to make 2 calls from the API (or use OrderStatus.All and process / skip over the items you don't want.

The PR would be to add an override for `GetAllOrdersAsync `that takes a  something like a `List<OrderStatus>` ... or maybe make the enum a flag - allow them to be combined... and then allow them to be separated, but this creates problems with `OrderStatus.All` and maybe `OrderStatus.Active` ?

Way forward would seem to be dictated by how GDAX may apply error handling to the input.... is it ok to ask for same enum twice? is it ok to ask for .All and .Open at once etc?
