### ISSUE TITLE
'Websocket needs to be in the opened state. The current state is Connecting'

### ISSUE THREAD

**Issue by guanm326** [dougdellolio/coinbasepro-csharp#136]
I've been running with the App for about a week non-stop but today I got the following error inside the Websocket.Stop() method. Is this called when we lose internet connection?

Is there anything I can do to prevent this?

Additional info: So my program is listening to the Level2 and Match channel. The initial cause of the problem was when an level2 update came with a price level change that my internal orderbook did not have. When this happens, my program will restart to get a fresh start to make sure my orderbook is correct.

Thanks

**Comment by dougdellolio** [comment]
i haven't seen this before. i don't see any reason why stop would be called if internet connection is lost. when you are restarting your program are you calling stop then? Also, logging has been recently added here now it might best to trace it using the log messages... wish I could give you a better answer.

**Comment by BradForsythe** [comment]
Hi @guanm326 - The web socket doesn't really know if you lose the internet connection.  You will know quickly though as soon as you try to send something, one of the error callbacks will be thrown.   There are all kinds of keepalive strategies, one way is to expect L2 data on your channels and if you lose that assume something happened to the connection or GDAX.   

Chances are when you get an L2 update and you don't find a price match in your order book you are not stopping the subscription and restarting.   Pretty much just close and reopen the websocket.   But be aware to do some checks so you don't get caught in a crazy loop...connect...error...conect...error...etc.  You will overrun your PC resources.  Use some retry delays etc.

All of that said....you may have a deeper problem.   You are saying when you get a price update for a price not in your order book you are going to "restart the program"    Firstly, L2 book can be quite large  up to 30,000 bid and ask entries.  Make sure you have your code written with performance in mind when searching for the price level that matches the updates.   If you are dropping updates and only notice when the price doesn't match, then chances are you have other defects in your order book.    

When I dig out of my hole, I will submit my Level 2 book manager.   I run 7 books simultaneously without issue.    

Just yesterday I did notice that I could not subscribe to the BCH-USD L2 channel.  But it's back now.
