### ISSUE TITLE
Order Handling

### ISSUE THREAD

**Issue by guanm326** [dougdellolio/coinbasepro-csharp#147]
Hi, I have a couple of questions on how best to handle orders as they go through various status. Please let me know if there are better ways to handle the description I provide below on how I am managing orders. Thanks

Right now given my theoretical price, my algo will submit a new order with `PlaceLimitOrderAsync` method.  Once that is submitted, and I am return with a OrderResponse object, I will call on OnOrder method that will update my internal variables that track the open orders I have in the market.  A couple of things can happen after this:

1. The algo order was manually cancelled on the website (human intervention). Once I submitted an order, I am calling `GetOrderByIdAsync` on every **tick** to get the status of the order. From the examples on the front page, this isn't a paged response but will I ever get IP blocked for constantly requesting this information? Next when I manually deleted the order, calling `GetOrderByIdAsync` doesn't seem to return anything anymore. Is there a way to get information on that order? If it is cancelled, I would need to be notified somehow so I can change my internal records. I think if there is a way for Coinbase to notify me about the status of the order, I wont have to constantly call `GetOrderByIdAsync` .

2. The order is filled. Will I get some sort of event from Coinbase telling me my order is filled? From looking at the code and the docs, it seems its my responsibility to determine whether I am filled or not. What is the best/fastest way to determine whether I am filled or not? All the GetFills method are paged so I have a limit as to the number of times I query...

I am a bit confused on how to handle the above, love to hear how others are doing it thanks.

**Comment by guanm326** [comment]
Ok for `2.` I think the solution is to listen to OnMatch messages and check if the trades that are coming through have any thing relating to the order id i have.

**Comment by dougdellolio** [comment]
@guanm326 

There shouldn't be a problem with calling `GetOrderByIdAsync` as long as you stay within their rate limits. You can read about them here: https://docs.pro.coinbase.com/#rate-limits.

If you want to go the websocket route the `OnMatch` will let you know when a trade has occurred between two orders. But I think what you want is the `OnDoneReceieved` event to let you know when the order is no longer on the order book. This results from an order being cancelled or filled. This will come back with a remaining size and a reason (such as filled). You should subscribe to the full channel for that. Read more about `Done` here https://docs.pro.coinbase.com/#the-code-classprettyprintfullcode-channel.

let me know what you think

**Comment by guanm326** [comment]
Yup I think that makes sense. 

With your suggestion now I have another problem I am not sure how to work around. When my theo price changing constantly I need to be able to cancel orders after a new theo price event occurs.

Right now I have no problem sending orders on a theo price change but I am not able to cancel the old orders asynchronously. For example, lets assume I receive a tick and calculate my theo price. With new theo price, I send my order. Now before I get any order response or any other order information acknowledging my order, I receive another tick which requires another order change. On this second theo price change, I can't find information on my first order to cancel since I haven't received anything yet. Given its asynchronously processing order submission, I now have 2 orders in to market. I only want the second order. How would you go about handling this?

**Comment by dougdellolio** [comment]
unfortunately, i dont think I would be able to provide any help on this issue. Thinking out loud, you should essentially not send another order on a subsequent tick until the previous order was received and a cancellation was requested. You should wait on the first order to actually return a cancellation response before sending a new order. This may mean missing opportunities though which may or may not be okay depending on your strategy. In terms of implementing this I am not sure tbh. i haven't run into this issue but perhaps someone else has that could provide a more helpful response 😄

**Comment by guanm326** [comment]
thanks Doug. I actually figured it out with my developer. We coalesce the theo to avoid rate limits and utilized another separate thread (with queue) to sychronized the entire process.

**Comment by dougdellolio** [comment]
excellent 😄 will close this issue
