### ISSUE TITLE
GetAllAccountsAsync() issue?

### ISSUE THREAD

**Issue by GITMIKRO** [dougdellolio/coinbasepro-csharp#148]
@dougdellolio I have recently starting seeing a null value returned for the following, which has worked before.

`var result = await CoinbasePro.AccountsService.GetAllAccountsAsync();`

Any suggestions for what I may have missed?

**Comment by dougdellolio** [comment]
@GITMIKRO the fix is in here: https://github.com/dougdellolio/coinbasepro-csharp/pull/150

i will release next version tomorrow. thanks 👍

**Comment by GITMIKRO** [comment]
@dougdellolio I updated to 1.0.21, but still receing null data on the result. thx!
