### ISSUE TITLE
GetAllProductsAsync() error

### ISSUE THREAD

**Issue by atswork** [dougdellolio/coinbasepro-csharp#149]
API need to be updated!

When invoke GetAllProductsAsync Function, it got an error: Requested value 'ETC-USD' was not found

Cause Shares/Types/ProductType Not Support

**Comment by wall2in** [comment]
I got the same problem，also ETC-EUR and ETC-BTC!

I fix it myself and make it work now, 
but hope developer could provide next stable release as soon as possible.

**Comment by GITMIKRO** [comment]
@wall2in can you share what it is and where you made your fix? Thank you and much appreciated.

**Comment by dougdellolio** [comment]
@atswork @wall2in @GITMIKRO looks like coinbase added support for ethereum classic yesterday. i have added this in here: https://github.com/dougdellolio/coinbasepro-csharp/pull/150.

will get this in as soon as possible, thanks!
