### ISSUE TITLE
FillsService before=

### ISSUE THREAD

**Issue by bwjunkie** [dougdellolio/coinbasepro-csharp#155]
/fills?before=

I don't see an implementation for this option, is it deprecated?

-Josh

**Comment by dougdellolio** [comment]
@bwjunkie hey I don't see any option for this in their API docs currently. Are you seeing this somewhere? Would be happy to add if it's possible!

**Comment by bwjunkie** [comment]
This may be my mixup with Pagination, in the docs they show:

example GET /orders?before=2&limit=30
API Pagination section
before |   | Request page before (newer) this pagination id.
after |   | Request page after (older) this pagination id.
limit | 100 | Number of results per request. Maximum 100. (default 100)
