### ISSUE TITLE
ZRX Currency type needed

### ISSUE THREAD

**Issue by bwjunkie** [dougdellolio/coinbasepro-csharp#158]
AccountsService.GetAllAccountsAsync maybe just broke in the last 24 hrs, due to CoinbasePro's new currency type.

Error converting value ""ZRX"" to type 'CoinbasePro.Shared.Types.Currency'

**Comment by bwjunkie** [comment]
Things worked for me once I appended,

public enum Currency
    {...   , ZRX

and

 public enum Producttype
  {...   , [EnumMember(Value = "ZRX-USD")]
        ZrxUsd

**Comment by dougdellolio** [comment]
@bwjunkie please update to the latest version in nuget (v1.0.22) for this fix. thanks!
