### ISSUE TITLE
Support dynamic products at runtime

### ISSUE THREAD

**Issue by mchandschuh** [dougdellolio/coinbasepro-csharp#163]
When connecting to the websocket I will typically fetch a listing of all products from coinbase, convert them to `ProductType` and then pass those converted values to the websocket. This process can fail each time coinbase issues a new product due to `ProductType` being an enum. We can convert `ProductType` into a class, provide the required equality members and custom json serializers to maintain existing behavior with minimal code changes. I've implemented something similar in [my fork](https://github.com/1Konto/coinbasepro-csharp/issues/1). Again, apologies for the lacking unit tests, but I have confirm the websockets, balances, and list products endpoints all work as advertised. Perhaps someone can pick this up, add the tests and then we'll have a mergeable PR.

Here's [`ProductType`](https://github.com/1Konto/coinbasepro-csharp/blob/d63378950b86d7ddaca580b31612c340f2935bf1/CoinbasePro/Shared/Types/ProductType.cs) converted into a class. The secret sauce is properly serializing the complex type as a value type using the `TypeChangeJsonConverter`

**Comment by dougdellolio** [comment]
@mchandschuh i have been going back and forth on this for some time. I do like your idea but it would definitely be a breaking change which I want to try to avoid. I also feel like in this case the `enum` keeps the concept of `ProductType` simple and lightweight.

One of the ideas I was playing with is setting the `ErrorContext.Handled` flag on the JsonSerializerSettings (https://github.com/dougdellolio/coinbasepro-csharp/blob/master/CoinbasePro/Shared/Utilities/JsonConfig.cs#L17) to mark the error as handled and just log the event as an error. This would prevent 
the entire application from coming down just because it couldn't deserialize a new type.

You would add `args.ErrorContext.Handled = true;` just above the if statement.

One potential downside with this solution is that it could possibly hide errors in other parts of the application which may or may not be desired. 

do you have any thoughts around this? also open to any other ideas  😄

**Comment by chrisw000** [comment]
enum ProductType could have a ProductType.Unknown = 0

Have it serialize to that? And log it as a warning?

**Comment by dougdellolio** [comment]
@chrisw000 i like that idea too. how would the EnumMember in ProductType look though since it looks like it requires a set value?

**Comment by chrisw000** [comment]
Have it as something like Unknown-Unknown, and have Currency.Unknown = 0 defined within the Currency enum?

The base currency / quote currency extension helpers split the ProductType EnumMember on the hyphen, so whatever is picked as the currency value (and therefore determines the ProductType EnumMember value) doesn't *have* to be 3 characters... can be whatever value makes most sense and would never be an actual currency, now or in the future.


[an Enum should have a None or Unknown = 0 value as good practice](https://stackoverflow.com/questions/24151354/is-it-a-good-practice-to-add-a-null-or-none-member-to-the-enum
)

Currently the ProductType.BtcUsd == 0 (as its defined first)

**Comment by chrisw000** [comment]
Alternatively.... Coinbase have announced the coins they're considering adding, and so far they've added the new ones paired to BTC USD EUR -> so could just add all the possible new ones so they're their for if / when they are made live?

And perhaps put the above Unknown fallback handling in just incase?

**Comment by dougdellolio** [comment]
looks like we will have to implement custom JsonConverters for both `ProductType` and `Currency`. If you agree I will try to get to this today. Otherwise I can get this in next week as I am going on holiday for a week

**Comment by chrisw000** [comment]
[Actually a month or so ago they've said they'll accelerate new listings.](https://blog.coinbase.com/new-asset-listing-process-a83ef296a0f3)

And some listings maybe only available in some regions... so some ProductType values could be invalid for some users, even when they're live.

So sticking with the fixed enum long term could become problematic to keep it up to date for everyone?

The class route described above does also sound good long term... perhaps the API also provides some helper class to prebuild a List<ProductType> of everything thats available to the user at runtime?

Maybe the answer is to go with the quick fix for now and plan to swap to the class solution as a major release sometime in the future?

**Comment by dougdellolio** [comment]
sounds good. i have added a quick fix here for now and will revisit when I am back. .https://github.com/dougdellolio/coinbasepro-csharp/pull/164 if no objections I will merge and release new version

**Comment by scholtz** [comment]
hi, new product has been added to coindesk .. can you please merge this and release new version? thanks

**Comment by chrisw000** [comment]
They've added 4 more currencies:
https://blog.coinbase.com/erc20-tokens-civic-cvc-district0x-dnt-loom-network-loom-and-decentraland-mana-are-b1af2f53d92b

And are looking at a whole load more:
https://blog.coinbase.com/coinbase-continues-to-explore-support-for-new-digital-assets-92ba4ab7f465
