### ISSUE TITLE
No nuget updated version released since v1.0.23

### ISSUE THREAD

**Issue by LeonardoX77** [dougdellolio/coinbasepro-csharp#173]
Hi Doug
Since v1.0.23 it has been several improvements and fixes but no new version has been released into nuget.
I think this latest changes are enough important to release a new version. What are the indicators you apply or follow to label and release a new version?

Thanks
Regards

**Comment by dougdellolio** [comment]
hey @LeonardoX77. Just released the latest to Nuget, sorry bout that. No real indicators to release.... just as changes queue up 😄 will close so feel free to reopen if you see any issues

**Comment by LeonardoX77** [comment]
no problem, thanks to you for all your dedicated effort ;)
