### ISSUE TITLE
No ticker-messages on WebSocket when using API-Key that is restricted to an IP-address

### ISSUE THREAD

**Issue by michaelhuber1937** [dougdellolio/coinbasepro-csharp#174]
I have just created an API-Key on CoinbasePro that it is restricted to a specific IP-address (for security reasons).

But the problem is now that now I don't get any ticker messages via the WebSocket anymore. Calls to CoinbasePro with the same api key are working perfectly, so the credentials are fine.

When I switch back to an API-Key that is *NOT* restricted to an IP-address, I am receiving the ticker messages without any problems.

So my questions is, is this a bug or a intended behaviour of CoinbasePro?

Best,
Michael

**Comment by michaelhuber1937** [comment]
Since this feature is very important to me, I already digged into the code. In fact the message is received (a websocket message was sent by CoinbasePro):

> {"type":"error","message":"Sorry, you could not be authenticated: Unauthorized","reason":"IP does not match IP whitelist"}

This results in a ResponseType.Error and therefore no event was fired.

The IP-address is definitly on the whitelist and all others calls except WebSocket does work.

Is the fault on the CoinbasePro-side? Maybe there is a 2. whitelist for WebSockets?

**Comment by dougdellolio** [comment]
hey @michaelhuber1937. I tried looking around and can’t seem to find anymore information around it elsewhere. I can also try later today using my own credentials to see if I get the same error. 

Did this work for you in previous versions of this library? If no then I would probably reach out to support on Coinbases end. They usually respond quickly if you use the reason for contact under API. 

The only other thing I can recommend is to maybe try removing your key and creating a new one if you haven’t already. 

I’ll get back to you later today.

**Comment by dougdellolio** [comment]
I am seeing the same issue. Digging around some more and it looks like it's a known issue: https://github.com/coinbase/gdax-node/issues/201

Depending on what you are trying to do, a workaround "solution" from that thread is to use a read-only API key without an IP filter for web socket and then use the IP filtered key via REST to do any trade operations. 

Wish I had a better answer for you!

**Comment by michaelhuber1937** [comment]
I have a better idea. You overload the contructor with another parameter Authentication-Object, e.g. "authenticationWebSocket" and use that for the websocket. If this parameter is null, no authentication will be done, so the public WebSocket is used.

The standard-constructor just passes the same object of authentication to both internally.

> Depending on what you are trying to do, a workaround "solution" from that thread is to use a read-only API key without an IP filter for web socket and then use the IP filtered key via REST to do any trade operations.

Good idea as well, but I don't prefer this solution since then we have two WebSocket-connections. Although it works.

**Comment by michaelhuber1937** [comment]
@dougdellolio

What do you think?
