### ISSUE TITLE
Conversion Error of AccountEntryType

### ISSUE THREAD

**Issue by ryanfalzon** [dougdellolio/coinbasepro-csharp#180]
Getting the error below when invoking the method 'AccountsService.GetAccountHistoryAsync'

> Newtonsoft.Json.JsonSerializationException: 'Error converting value "conversion" to type 'CoinbasePro.Services.Accounts.Types.AccountEntryType'. Path '[0].type', line 1, position 145.'

**Comment by dougdellolio** [comment]
hi @ryanfalzon thanks for catching this. I have added a fix here: https://github.com/dougdellolio/coinbasepro-csharp/pull/181 this also contains a change that will prevent this from happening ever again should they add another type. New types will be set to `Unknown`

**Comment by ryanfalzon** [comment]
Will this update be releases in nuget?
