### ISSUE TITLE
OnTickerReceived receives only one message and stops

### ISSUE THREAD

**Issue by m1stegmann** [dougdellolio/coinbasepro-csharp#187]
OnTickerReceived receives only one message and stops.

OnErrorReceived and OnWebSocketError are without any error.

Doesn't work with and without authentication.

Any hints?

**Comment by dougdellolio** [comment]
hey @m1stegmann. what channels are you subscribing to and what product types are you using? I am able to receive all messages

**Comment by m1stegmann** [comment]
Sorry, if i turn sandbox off it's working!
