### ISSUE TITLE
GetAllAccountsAsync

### ISSUE THREAD

**Issue by gggustavo** [dougdellolio/coinbasepro-csharp#197]
when call coinbaseProClient.CoinbaseAccountsService.GetAllAccountsAsync()
return ->  'Newtonsoft.Json.JsonSerializationException' en System.Private.CoreLib.dll: 'Error converting value "ETH" to type 'System.Guid'. Path '[3].id', line 1, position 989.'

Assembly CoinbasePro, Version=1.0.28.0

**Comment by dougdellolio** [comment]
hey @gggustavo. i've tested out different environments and can't seem to replicate this. is there any more information you can provide? either the json response (omitting all sensitive information) or what type of account it is trying to deserialize. thanks

**Comment by gggustavo** [comment]
If I try call coinbaseProClient.**AccountsService**.GetAllAccountsAsync() work, instead
coinbaseProClient.CoinbaseAccountsService.GetAllAccountsAsync()

thank for support
