### ISSUE TITLE
CoinbasePro.WebSocket.Models.Response.Match missing fields

### ISSUE THREAD

**Issue by bthtrade** [dougdellolio/coinbasepro-csharp#198]
When subscribed to the Match messages, being authenticated, API Reference says:

> If authenticated, and you were the taker, the message would also have the following fields:
taker_user_id: "5844eceecf7e803e259d0365",
user_id: "5844eceecf7e803e259d0365",
taker_profile_id: "765d1549-9660-4be2-97d4-fa2d65fa3352",
profile_id: "765d1549-9660-4be2-97d4-fa2d65fa3352"

Those fields are not present in the CoinbasePro.WebSocket.Models.Response.Match class.
Would it be possible to add those?

**Comment by dougdellolio** [comment]
added in #199. thx

**Comment by nicbavetta** [comment]
This model is currently out of date. [See here](https://docs.pro.coinbase.com/#the-full-channel).

If the user is the maker, the following data will be included in the response:

```
maker_user_id: "5f8a07f17b7a102330be40a3",
user_id: "5f8a07f17b7a102330be40a3",
maker_profile_id: "7aa6b75c-0ff1-11eb-adc1-0242ac120002",
profile_id: "7aa6b75c-0ff1-11eb-adc1-0242ac120002",
maker_fee_rate: "0.001"
```

If the user is the taker, the following data will be included in the response:

```
taker_user_id: "5844eceecf7e803e259d0365",
user_id: "5844eceecf7e803e259d0365",
taker_profile_id: "765d1549-9660-4be2-97d4-fa2d65fa3352",
profile_id: "765d1549-9660-4be2-97d4-fa2d65fa3352",
taker_fee_rate: "0.005"
```

Therefore, the following properties should be added:

- maker_user_id
- maker_profile_id
- maker_fee_rate
- taker_fee_rate
