### ISSUE TITLE
Easiest way to convert string to ProductType and vice versa?

### ISSUE THREAD

**Issue by henningms** [dougdellolio/coinbasepro-csharp#202]
Hello,

I'm wondering. What's the easiest way to convert to and from ProductType?

**Comment by dougdellolio** [comment]
hi @henningms. There is an extension method that exists on enum (that should give you what you are looking for to convert from ProductType to string https://github.com/dougdellolio/coinbasepro-csharp/blob/master/CoinbasePro/Shared/Utilities/Extensions/EnumExtensions.cs#L11. There is no elegant way currently that will convert from string to ProductType but you can use the generic parse method on an enum if you are interested. I haven't seen a case where it is needed within the library but let me know if you think otherwise.

For example:

ProductType to string ->
```csharp 
var stringValue = ProductType.BchGbp.GetEnumMemberValue();
```

hope this helps!

**Comment by henningms** [comment]
Hi there @dougdellolio,

Within the library it might not be necessary, or wait, there's already something that parses ProductType from a JSON string right? 

I'm thinking of using this library in conjunction with other libraries for other exchanges for some small trading scripts that can read a trading pair from an editable configuration file and have it easily map to the correct ProductType in this case. 

It's not a big deal, but might be something that would please other users of the library in the future? 

What are your thoughts on this idea?

Example of such thing
```csharp
var productType = ProductType.FromString("BTC-EUR");
```

**Comment by dougdellolio** [comment]
sure, why not. feel free to take a stab at it otherwise I can get to it when I have some time.

**Comment by mchandschuh** [comment]
@henningms -- any progress? I actually converted this repo about a year ago to _not_ use an explicit enumeration, but instead use a static enumeration class. This was to fix the issue with the application crashing each time coinbase adds a new coin. I can't remember if I offered it as a PR or not. Here's the main commit that may be of interest to you:
> https://github.com/1Konto/coinbasepro-csharp/commit/3c83497b39ce1ed83250774f2b82c753b29b4364

the concept is simple -- convert the `ProductType` enumeration and `Currency` enumeration into a class that simply wraps a string. This allows serialization/deserialization to happen correctly, even if the repo hasn't been updated with the most recent coins. The 'enumeration' behavior becomes more of a syntax friendliness rather than an application requirement.

**Comment by henningms** [comment]
Ah, cool.

I did not get around to doing anything I'm afraid. My trading apps had to take a backseat for a while.

**Comment by salocinx** [comment]
@mchandschuh What do you mean by:

`This was to fix the issue with the application crashing each time coinbase adds a new coin. `

Does your application based on this library really crash when a new coin is added to Coinbase or is the new coin just not available in your application? If it indeed crashes, why?

**Comment by salocinx** [comment]
I guess to solve the issue with new coins, one would have to refactor all `ProductType` enum occurrences with a `string` type within this library. Then requesting all available products by calling `client.ProductsService.GetAllProductsAsync()` on application startup (or periodically) and build up a collection of strings identifying the available products which then can be used to place orders etc. Would this be the "simplest" solution to make the library new-coin-proof?

**Comment by oscar54321** [comment]
I created class below to help solve this problem to string to enum conversions. 

```

using CoinbasePro.Shared.Types;
using CoinbasePro.WebSocket.Types;
using System;
using System.Collections.Generic;
using System.Reflection;
using System.Runtime.Serialization;
using System.Text;

namespace xxx
{ 
    public class CoinbaseEnumConverter 
    {
        private Dictionary<Type, Dictionary<string, object>> FromValueMap;

        private Dictionary<Type, Dictionary<object, string>> ToValueMap;

        public CoinbaseEnumConverter(Type[] enumTypes)
        {
            foreach (Type enumType in enumTypes)
                InitMap(enumType);
        }

        private void InitMap(Type enumType)
        {
            if (FromValueMap == null)
            {
                FromValueMap = new Dictionary<Type, Dictionary<string, object>>();
            }

            if (ToValueMap == null)
            {
                ToValueMap = new Dictionary<Type, Dictionary<object, string>>();
            }

            if (FromValueMap.ContainsKey(enumType))
            {
                return;
            }

            var fromMap = new Dictionary<string, object>(StringComparer.InvariantCultureIgnoreCase);
            var toMap = new Dictionary<object, string>();

            var fields = enumType.GetFields(BindingFlags.Static | BindingFlags.Public);

            foreach (var field in fields)
            {
                var name = field.Name;
                var enumValue = Enum.Parse(enumType, name);

                var enumMemberAttrbiute = field.GetCustomAttribute<EnumMemberAttribute>();

                if (enumMemberAttrbiute != null)
                {
                    var enumMemberValue = enumMemberAttrbiute.Value;

                    fromMap[enumMemberValue] = enumValue;
                    toMap[enumValue] = enumMemberValue;
                }
                else
                {
                    toMap[enumValue] = name;
                }

                fromMap[name] = enumValue;
            }

            FromValueMap[enumType] = fromMap;
            ToValueMap[enumType] = toMap;
        }

        public string ToValue(Type enumType, object obj)
        {
            var map = ToValueMap[enumType];

            return map[obj];
        }

        public object FromValue(Type enumType, string value)
        {
            var map = FromValueMap[enumType];

            return !map.ContainsKey(value)
                ? null
                : map[value];
        }

        private static readonly CoinbaseEnumConverter _coinbaseEnumConverter = new CoinbaseEnumConverter(new[] { typeof(ProductType), typeof(ChannelType) });

        public static CoinbaseEnumConverter Instance
        {
            get => _coinbaseEnumConverter;
        }
    }
}

```

**Comment by damien-alchemylabz** [comment]
if it helps anyone ...

 private async Task<ProductType> GetProductType(string productstring)
        {
            ProductType item = (ProductType)Enum.Parse(typeof(ProductType), productstring);
            return item;
        }
