### ISSUE TITLE
Async Methods

### ISSUE THREAD

**Issue by geniosoft** [dougdellolio/coinbasepro-csharp#207]
Hello,

I am using your library but i am working in VB.NET, and the async functions are making me dificullties.

I can't seem to make it work. I could go to C# and follow your examples, but i know that later in the most advanced features my experience in VB will make me go faster, but now it is difficult to make it work, because i am not used to work with async functions.

My code is as follows, the connection to the client is OK, but i don't get anyting from the products type:

    Dim apikey As String = "xpto"
    Dim apisecret As String = "xyz"
    Dim passphrase As String = "ABC123"
    Dim usesandbox As Boolean = False

     Dim auth1 As New CoinbasePro.Network.Authentication.Authenticator(apikey, apisecret, passphrase)
     Dim client1 As CoinbaseProClient
     client1 = New CoinbaseProClient(auth1, usesandbox)

     Dim productstask1 As Task(Of IEnumerable(Of Services.Products.Models.Product)) = client1.ProductsService.GetAllProductsAsync()

How can i start productstask1 and get a result? I think that for every async function the solution will be the same...

Thanks in advance.

**Comment by dru-ward** [comment]
Hi,

Not familiar with VB, but without an await in C# you can put .Result on the end to get the result of the task (non async).. don’t know if it will work in VB, but replace your last line with: 

Dim productstask1 As Task(Of IEnumerable(Of Services.Products.Models.Product)) = client1.ProductsService.GetAllProductsAsync().Result

Let me know how you get on. 

Thanks

**Comment by geniosoft** [comment]
Hello, thank you for your help. 

I also contacted a friend that both works with C# and VB and he helped me solve the problem.

Your suggestion of using .Result or using Await before, both can do, but only if i declare the function where this code is as async:

Private Async Sub Stuff_to_Do()
          [....]
          Dim productstask1 As IEnumerable(Of Services.Products.Models.Product) = Await client1.ProductsService.GetAllProductsAsync()
          [...]
End Sub

This above works.
Thank you very much.
