### ISSUE TITLE
I gen a CoinbasePro.Exceptions.CoinbaseProHttpException: Post only mode

### ISSUE THREAD

**Issue by codeinflash** [dougdellolio/coinbasepro-csharp#208]
Hi,
Sometimes, I get an error when placing a limit sell order.
The stack trace is below:

Exception - CoinbasePro.Exceptions.CoinbaseProHttpException: Post only mode
   at CoinbasePro.Services.AbstractService.SendHttpRequestMessageAsync(HttpMethod httpMethod, String uri, String content)
   at CoinbasePro.Services.AbstractService.SendServiceCall[T](HttpMethod httpMethod, String uri, String content)
   at CoinbasePro.Services.Orders.OrdersService.PlaceOrderAsync(Order order)
   at CoinbasePro.Services.Orders.OrdersService.PlaceLimitOrderAsync(OrderSide side, ProductType productId, Decimal size, Decimal price, TimeInForce timeInForce, Boolean postOnly, Nullable`1 clientOid)

**Comment by dougdellolio** [comment]
hi @codeinflash 

For post only mode, the post only flag is invalid when time_in_force is IOC or FOK. Are you using either of those values in your call? Looking through the docs, another piece of info which may or may not be related is `The post-only flag indicates that the order should only make liquidity. If any part of the order results in taking liquidity, the order will be rejected and no part of it will execute.`

If this still doesn't help, please paste the exact call you are making (omit quantities and prices) and I can try and help debug from there.

thanks!

**Comment by codeinflash** [comment]
Hi @dougdellolio 

I use the built-in limit sell order function as following:
var orderResponse = await _CoinbaseProClient.OrdersService.PlaceLimitOrderAsync(CoinbasePro.Services.Orders.Types.OrderSide.Sell,
                CoinbasePro.Shared.Types.ProductType.BtcUsd, correctOrderSize, currentPrice);

**Comment by dougdellolio** [comment]
hmmm.. from my understanding you wouldn't be able to set a price that is the same or lower than the highest buy order.

Wish I could help more.... if you do find out the answer please post back for future reference
