### ISSUE TITLE
Is there a feature I can pull real-time hourly volume?

### ISSUE THREAD

**Issue by codeinflash** [dougdellolio/coinbasepro-csharp#209]
Hi @dougdellolio,
Hope you are well.
Is there a way to pull hourly volume of BTC-USD?
Like when you select 1hr chart in TradingView, you can see current real-time volume.

Thanks!

**Comment by dougdellolio** [comment]
@codeinflash i think what you want is `GetHistoricRatesAsync(..)` under the `Products` service on the client.. This call will return you [ time, low, high, open, close, volume ] given a timeslice (aka the granularity). You can see that granularity options here: https://github.com/dougdellolio/coinbasepro-csharp/blob/master/CoinbasePro/Services/Products/Types/CandleGranularity.cs.

Some more around the docs here: https://docs.pro.coinbase.com/#get-historic-rates)

Let me know if this is not what you were looking for 😄

**Comment by dougdellolio** [comment]
Looking through the docs again I am not sure of any other way, sorry. You can try maybe reaching out to Coinbase directly to see if they can offer a solution or wait and see if another user here has a better idea.
