### ISSUE TITLE
CandleGranularity

### ISSUE THREAD

**Issue by j0sh710** [dougdellolio/coinbasepro-csharp#212]
Can you add the 4h candle granularity?

**Comment by dru-ward** [comment]
I could be wrong, but I’m confident in saying that the Coinbase Pro Api doesn’t support 4h candle data.

**Comment by dougdellolio** [comment]
hey @j0sh710, i think @dru-ward  is right. From their docs i don't see an option for 4hr:

> The granularity field must be one of the following values: {60, 300, 900, 3600, 21600, 86400}. Otherwise, your request will be rejected. These values correspond to timeslices representing one minute, five minutes, fifteen minutes, one hour, six hours, and one day, respectively.

**Comment by j0sh710** [comment]
Thank you @dougdellolio and @dru-ward I now see that and you are correct. I appreciate you looking into it!
