### ISSUE TITLE
Open order for LINK-USDC shows up as 'Unknown' Product Id

### ISSUE THREAD

**Issue by axelarati** [dougdellolio/coinbasepro-csharp#214]

**Comment by dougdellolio** [comment]
hi @axelarati . I don't see that trading pair as available on Coinbase Pro which is why it could be Unknown. I am looking at their list here: https://support.pro.coinbase.com/customer/en/portal/articles/2945308-locations-and-trading-pairs

Also make sure you have latest version from Nuget as the LINK currency was added in v1.0.30 which could be another reason you are seeing Unknown.

**Comment by axelarati** [comment]
Thanks for your reply. I think this trading pair is available on Coinbase Pro because I was able to see the LINK-USDC order with a different API (https://github.com/bchavez/Coinbase.Pro). I also had manually created that order using the coinbase pro UI, but I noticed that the UI only has around 5-6 trading pairs and those pairs seem to be different than the ones in the link you provided.

**Comment by confessore** [comment]
I don’t see this pair. I only see LinkUsd and LinkEth

**Comment by dougdellolio** [comment]
I am still not sure how it is possible as I don't see this on their listed markets either (only LinkUSD and LinkETH as the other comments state) (https://pro.coinbase.com/markets) or through my trading UI. Could you maybe provide a screenshot of some sort of where you are seeing this?

**Comment by axelarati** [comment]
I think it's because I am testing in the sandbox. You can see in the screenshot below that there is 'LINK-USDC' as a market.

![Screen Shot 2019-12-25 at 1 56 08 PM](https://user-images.githubusercontent.com/16293515/71449626-83164b80-271e-11ea-9630-6b31209b61ca.png)

**Comment by confessore** [comment]
not sure if @dougdellolio wants to add pairs that are only in the sandbox. it makes sense that coinbasepro would add these features to the sandbox before going live with them

**Comment by dougdellolio** [comment]
sandbox definitely explains this. my thought here is to hold off on adding these until they are fully supported on their live servers. I wouldn't want to give anyone the impression they can trade this before it's available. Until then, I would recommend either forking this project and adding it for your own use or choosing another pair to test with. hope this clears it up!
