### ISSUE TITLE
Error Converting Value "LOOM" to type 'System.Guid'

### ISSUE THREAD

**Issue by ThatBlokeCalledJay** [dougdellolio/coinbasepro-csharp#218]
Hello all,

Just trying out the various services and hit across this problem, seems pretty straight forward but just wanted to report it.

When I use the CoinbaseAccountsService.GetAllAccountsAsync method, I get the above error. On inspection of the json data, it's clear to see that some of the accounts have, as expected, GUIDs but other accounts seem to have the actual currency value set as the id.

Here's a snapshot of the data that's being returned from the api.

```
{
        "id": "27386189-c528-5988-89f0-114389046db3",
        "name": "BTC Wallet",
        "balance": "0.00000000",
        "currency": "BTC",
        "type": "wallet",
        "primary": true,
        "active": true,
        "available_on_consumer": true,
        "hold_balance": "0.00",
        "hold_currency": "GBP"
    },
    {
        "id": "LOOM",
        "name": "LOOM Wallet",
        "balance": "0.00000000",
        "currency": "LOOM",
        "type": "wallet",
        "primary": false,
        "active": true,
        "available_on_consumer": false,
        "hold_balance": "0.00",
        "hold_currency": "GBP"
    }
```

The results contain 26 accounts in total. 11 seem to be classic accounts (LTC Wallet, ETH Wallet) with the expected GUIDs, the remaining ones seem to be somewhat newer currencies all with IDs representing their currency, e.g LOOM, MANA, DNT, CVC, ZIL etc. Looks like coinbase have perhaps ditched the GUID approach for a more human-readable id?

I was able to avert this error locally by switching out the CoinbaseAccount Id property type to string followed by updating the associated tests. Of course this could be troublesome for existing implementations.

**Comment by dougdellolio** [comment]
hi @ThatBlokeCalledJay thanks for catching this. I don't really understand why these are no longer all the same GUID type. Their documentation makes no note of this either and it seems to be a fairly new thing. I think switching the id to a string is the only option here even though it's breaking. 

change is made here https://github.com/dougdellolio/coinbasepro-csharp/commit/da0245c4dd9c3f39ea85334cc9047fb6836770a0 and will go out with the next release.

much appreciated!
