### ISSUE TITLE
Issue with placing market order (price = 0)

### ISSUE THREAD

**Issue by axelarati** [dougdellolio/coinbasepro-csharp#220]
When I call CoinbaseProClient.OrdersService.PlaceMarketOrderAsync() I get an error saying that price 0 is invalid. However, for market orders there shouldn't be a price specified, and the documentation confirms this. https://docs.pro.coinbase.com/#place-a-new-order

Maybe the API is accessing the wrong endpoint or Coinbase is incorrectly giving me back this error. I looked into the source code and it looks fine to me, so it is most likely Coinbase causing this.
https://github.com/dougdellolio/coinbasepro-csharp/blob/master/CoinbasePro/Services/Orders/OrdersService.cs 
https://github.com/dougdellolio/coinbasepro-csharp/blob/master/CoinbasePro/Services/Orders/Types/OrderType.cs

FYI I am running this on sandbox mode, so Coinbase might not be set up to take market orders on sandbox for some reason...

**Comment by dougdellolio** [comment]
@axelarati what version are you using? we saw this problem with versions < v1.0.34. Try upgrading if you haven't and see if that fixes. thanks!

**Comment by axelarati** [comment]
That worked, thanks!
