### ISSUE TITLE
Error with GetAllFillsAsync()

### ISSUE THREAD

**Issue by axelarati** [dougdellolio/coinbasepro-csharp#222]
When I try get all the fills I get this error message:
"query must contained either product_id or order_id"

I'm able to get fills when I query by product id.
This happens on sandbox mode, I have not tried live testing.

**Comment by dougdellolio** [comment]
hi @axelarati this was deprecated back in 2018.  I had also marked this as Obselete https://github.com/dougdellolio/coinbasepro-csharp/blob/master/CoinbasePro/Services/Fills/FillsService.cs#L22. I will remove completely soon. You will only be able to query by either product or order id.
