### ISSUE TITLE
Question getting Orders Continuous

### ISSUE THREAD

**Issue by ExceedingLife** [dougdellolio/coinbasepro-csharp#227]
Hello,
So I have a question.
I have a WPF application and I want to get continuous TradeHistory so if it goes to a price I can buy or sell.
What would be the best way to do this? Create a method and call 
ProductsService.GetTradesAsync
every 1 second?
I have never created an application to get continuous data.
Thank you (I wasn't sure where to post this)

**Comment by dougdellolio** [comment]
@ExceedingLife for continuous data I would recommend looking into using the websocket feed. please refer to the documentation here: https://docs.pro.coinbase.com/#websocket-feed and the Getting Started thread https://github.com/dougdellolio/coinbasepro-csharp/issues/118 for code examples. thanks
