### ISSUE TITLE
 Ticker High24H  always  0

### ISSUE THREAD

**Issue by pazi77** [dougdellolio/coinbasepro-csharp#228]
Hi Doug,
If you subscribe to the ticker channel
High24H always zero. I have not used the sandbox.
The other values should all be correct.

**Comment by dougdellolio** [comment]
hi @pazi77  thanks for reporting this. Definitely a bug. Fixed here: https://github.com/dougdellolio/coinbasepro-csharp/commit/a8e9a54ef129da7f2d429d4a172c54422c083e46. It will go out with next release
