### ISSUE TITLE
Websocket connection issue

### ISSUE THREAD

**Issue by ExceedingLife** [dougdellolio/coinbasepro-csharp#229]
Hello,
I'm trying to get a constant connection to the Websocket for order data,
I tried it with auth and no auth. both I get the error:
              "CoinbasePro.Exceptions.CoinbaseProWebSocketException: 'WebSocket Feed Error: A call 
               to SSPI failed, see inner exception.'"

I googled it and it told me to add 
```
           "const SslProtocols _Tls12 = (SslProtocols)0x00000C00;
            const SecurityProtocolType Tls12 = (SecurityProtocolType)_Tls12;
            ServicePointManager.SecurityProtocol = Tls12;"
```

but that didnt do anything. Any suggestions? Here is my code.
`private void btnStart_Click(object sender, RoutedEventArgs e)
        {
            try{
                    StartWebSocket();
               }catch(exception){}
        }
 public void StartWebSocket()
        {
            const SslProtocols _Tls12 = (SslProtocols)0x00000C00;
            const SecurityProtocolType Tls12 = (SecurityProtocolType)_Tls12;
            ServicePointManager.SecurityProtocol = Tls12;

            //var websocket = coinbaseProClient.WebSocket;
            var coinNoAuth = new CoinbasePro.CoinbaseProClient();
            var websocket = coinNoAuth.WebSocket;
            websocket.Start(productTypes, channelTypes);

            websocket.OnTickerReceived += (sender, e) =>
            {
                foreach(var bid in e.LastOrder.BestAsk.ToString())
                {
                    lstIncoming.Items.Add("Bid- " + bid);

                }
                //PrintData(e);
            };
        }
        private void PrintData(WebfeedEventArgs<Ticker> webfeedEventArgs)
        {
            lstIncoming.Items.Add("Bid- " + webfeedEventArgs.LastOrder.BestBid);
            lstIncoming.Items.Add("Ask- " + webfeedEventArgs.LastOrder.BestAsk);
        }
`

**Comment by dougdellolio** [comment]
@ExceedingLife Please make sure you're using the latest version. If you are downloading the package from Nuget, it should be v1.0.36.  https://github.com/dougdellolio/coinbasepro-csharp/releases/tag/v1.0.36
