### ISSUE TITLE
Retreiving Posted Orders by you

### ISSUE THREAD

**Issue by ExceedingLife** [dougdellolio/coinbasepro-csharp#230]
Hello Doug,

So I  got most everything working so far that I have been working on, I never looked back into websockets but Im getting all trade history every 3-5 seconds on a separate thread/task. So good enouph for now, 
Next I would like to see the orders/trades that I created, and to know if they have been completed or not. When I post for example a 'Stop Order' do I get the OrderID in the response object? I didnt double check this but if not I have no idea to see what order was created by me. Also how can I tell if the order was executed or not? 
What would be the best way to do this do you think?

**Comment by dougdellolio** [comment]
@ExceedingLife  please take a look at the docs here https://docs.pro.coinbase.com for these types of questions. you should be able to find the proper endpoints for orders and how to query types of orders here https://docs.pro.coinbase.com/#orders
