### ISSUE TITLE
System.AggregateException: 'One or more errors occurred. (Error converting value "9143hklo-d975-54df-bb60-64347682bfb7" to type 'System.Guid'. Path '[3].id', line 1, position 2290.)'

### ISSUE THREAD

**Issue by nicolae-lupei** [dougdellolio/coinbasepro-csharp#233]
![image](https://user-images.githubusercontent.com/56689983/84685760-75aa8300-af43-11ea-9437-2725577d9943.png)

**Comment by dougdellolio** [comment]
@nicolae-lupei  Are you seeing this in the live environment or just sandbox? I seem to be fine using non-sandbox. Regardless, I've updated to use string so this doesn't occur (https://github.com/dougdellolio/coinbasepro-csharp/commit/c3c3b926db3187b4a160ce5e017ad5b9af1f901c). Very weird it would be returning a non-valid GUID as their docs example has been GUIDs.

**Comment by nicolae-lupei** [comment]
I only used the sandbox environment
