### ISSUE TITLE
Max Funds For Limit Order

### ISSUE THREAD

**Issue by unholyHub** [dougdellolio/coinbasepro-csharp#238]
PlaceLimitOrderAsync(orderSide, productPair, size, price, timeInForce, postOnly, clientOId) - place limit order with time in force

I want to place a Limit Order with a specific price in mind.
The previous parameter of the method is size. 

I tried to calculate it with the this logic:
fee = currentBalance * LimitFee
(currentBalance - fee) / desiredPrice = size

But after executing the order in my balance always have a few USDs left in the available balance.
Is there any trick like in the Web interface when you click on balance amount it uses all the funds and places it for order and automatically subtracts the fee. 

After you place the order all the funds are set to that order.

**Comment by dougdellolio** [comment]
hi @unholyHub unfortunately, i don't think there is a way to do this currently . I just reviewed the docs again and don't see anything (https://docs.pro.coinbase.com/#orders).
