### ISSUE TITLE
XRP Withdrawal with Destinataion Tag

### ISSUE THREAD

**Issue by GITMIKRO** [dougdellolio/coinbasepro-csharp#240]
Hi Doug,

Using this to request a withdrawal to another wallet address:

var result = await CoinbasePro.WithdrawalsService.WithdrawToCryptoAsync(WithdrawToWallet, Convert.ToDecimal(withdrawalqty), currencyType);

With Ripple, the exchange I am sending to requires a Destination Tag.

Thanks for recommendation on how to do this.

Michael

**Comment by dougdellolio** [comment]
@GITMIKRO hey michael,

nice catch, this has been missing from this library since its new-ish to their API. I've just added the ability to specify destination tag and added other missing Withdrawal service calls: https://github.com/dougdellolio/coinbasepro-csharp/commit/e659de2723966b0f6b55b2a46def3a90a25e5d43. I released this to NuGet if you want to update to the latest and try. I have **not tested** the addition of the destination tag as thoroughly as I normally do because their sandbox doesn't allow for it although I have validated the requests looks good. I would suggest starting with a small amount first.

Let me know what you think or if you run into any issue

**Comment by GITMIKRO** [comment]
Thx Doug,

I will test as soon as possible. Always appreciated. I hope that you are safe and well.

Michael

**Comment by GITMIKRO** [comment]
@dougdellolio  

Strange... I updated to 1.0.38. I see the new destinationTag. I submit a valid wallet address and destination tag at the exchange where the XRP is being sent.  I get a valid Id response upon submission of the withdrawal request. 

However, the currency never leaves CoinBase.

Maybe I'm missing something obvious.  Any suggestions?

Thx.

**Comment by dougdellolio** [comment]
thanks Michael, hope you are safe and well too!

so a few things:

1. this endpoint requires that your API keys have the "transfer" permission. You can check this off when you create the keys. Without this checked, the withdrawals won't work
2. Transfers for XRP can take up to 600 seconds (10 minutes). If you have just put these orders in, I would give it some time to make sure it has gone through and avoid duplicating your orders
3. I would double check on the UI for the withdrawal history. You can view that here: https://pro.coinbase.com/portfolios/withdrawals and see if they provide any more detail into why it may not have gone through. Let me know if it doesn't appear still.

Hope this is helpful. Let me know if it's still not working

**Comment by GITMIKRO** [comment]
Good suggestions. 

I don't have access to my account atm, so when I do, I will check this out and report back:

1. I will first need to check the API keys and make sure I have the "transfer" permission set correctly. I have successfully transferred other currencies through coinbase, but I am not sure if I need to specifically set up an XRP key.

2. It isn't the transfer time. I did the first tests many hours ago.

3. I will definitely check the withdrawal history as well. 

Thx!

**Comment by GITMIKRO** [comment]
@dougdellolio Hi Doug,

Turns out, I was making a test withdrawal/transfer for an amount of XRP that was below the minimum.  Normally, in this situation, the API would respond with a message like "Amount is below the minimum (22.000 XRP), as I have seen with other currencies.   As I mentioned, the API responded here in a way that made me think the transfer request was accepted, by providing a unique identifier.

I don't know what response your API gets back from Coinbase, or if they provide that detail to you for XRP.

Thx !

**Comment by dougdellolio** [comment]
That's confusing. This library catches all errors as they are returned so it sounds like this may be something on their end. Not sure why XRP would be any different as the requests are the same. Were you able to confirm it works with an acceptable amount?

**Comment by GITMIKRO** [comment]
Thx @dougdellolio.  Yes,  It does work as long as I exceed the minimum quantity. I'll just trap that on my end so I don't make that mistake on some test in 6 months from now and forget that we resolved this.

**Comment by dougdellolio** [comment]
awesome, going to close this issue. let me know if you have any other issues!
