### ISSUE TITLE
GetAccountHistoryAsync  CoinbaseProHttpException: 'NotFound'

### ISSUE THREAD

**Issue by bwjunkie** [dougdellolio/coinbasepro-csharp#241]
Await coinClient.AccountsService.GetAccountHistoryAsync(walletid, 2, 2)

CoinbasePro.Exceptions.CoinbaseProHttpException: 'NotFound'

(ultimately trying to get my Fills)

example code:
 var accountsList = Await coinClient.CoinbaseAccountsService.GetAllAccountsAsync();
 var    walletThisProduct = From row In accountsList Where row.Currency = [Shared].Types.Currency.BTC select row;
var walletid = walletThisProduct.First().Id;
var result = Await coinClient.AccountsService.GetAccountHistoryAsync(walletid, 2, 2);

**Comment by dougdellolio** [comment]
hey @bwjunkie . Looking at your code, the `AccountsService` differs from the `CoinbaseAccountsService`. You are trying to pass in a Coinbase account ID in here so it is not being found. I would use the `AccountsService` to retrieve the ID of the account you want the history for. Your code should change to look something like this:

```csharp 
var accountsList = Await coinClient.AccountsService.GetAllAccountsAsync();
...
...
...

let me know if you are still seeing issues

**Comment by bwjunkie** [comment]
yes that helped, thank you.

now getting 'private rate limit exceeded'  *sad*  
but I'm sure that is not an API problem.

**Comment by dougdellolio** [comment]
yes, this endpoint has a special rate limit so you must be careful how you are calling this

> RATE LIMITS
> This endpoint has a custom rate limit by profile ID: 25 requests per second, up to 50 requests per second in bursts

feel free to open up another issue if you run into anything else. thanks!
