### ISSUE TITLE
Why is there no `MarketOrderAmountType` parameter for placing limit and stop orders?

### ISSUE THREAD

**Issue by salocinx** [dougdellolio/coinbasepro-csharp#242]
Thanks for sharing your great work!

Is there a reason why there is no `MarketOrderAmountType` parameter for placing limit and stop orders?

**Comment by dougdellolio** [comment]
hi @salocinx - thanks! I just double checked the API docs again and these look to be only available for Market Orders. Other order types only take a size (amount of base currency to buy or sell) while market orders are given the option to provide either funds or size amount. 

https://docs.pro.coinbase.com/#place-a-new-order

this looks to just be a limitation of their API

**Comment by salocinx** [comment]
Thanks for validating!
