### ISSUE TITLE
Fee Estimate ?

### ISSUE THREAD

**Issue by gggustavo** [dougdellolio/coinbasepro-csharp#245]
Hello!
I'm checking the coinbasepro api and there is a GET **/withdrawals/fee-estimate**. It would be great to have it.
Thanks in advance

**Comment by dougdellolio** [comment]
hey @gggustavo. This should now be added with https://github.com/dougdellolio/coinbasepro-csharp/commit/cff8be2f876bf1c254c2d334aa2d85be2950e35f. Please update to the latest version on NuGet for it (v1.0.39).

let me know if there are any issues. thanks!

**Comment by gggustavo** [comment]
@dougdellolio thanks!
