### ISSUE TITLE
Get single product missing in ProductsService.

### ISSUE THREAD

**Issue by JensKDK** [dougdellolio/coinbasepro-csharp#249]
Hi,

Would you please add:

public async Task<Product> GetProductAsync(
            ProductType productId)
{
    return await SendServiceCall<Product>(HttpMethod.Get, $"/products/{productId.GetEnumMemberValue()}").ConfigureAwait(false);
}

to ProductsService. I wish I could do it myself, but you have too many weird things going on in ProductsServiceSpecs, that I'm not confident, I wont screw it up. I'm pretty new to C#.

Thank you very much.

**Comment by dougdellolio** [comment]
hi @JensKDK. this is all set please update to the latest version on NuGet (https://github.com/dougdellolio/coinbasepro-csharp/releases/tag/v1.0.42)
