### ISSUE TITLE
"Invalid API key" error

### ISSUE THREAD

**Issue by oscar54321** [dougdellolio/coinbasepro-csharp#250]
Dear All,

I am trying to write a simple C# application that retrieves the list of accounts. However, I am getting an authentication error  "Invalid API Key". Could you please advise on what I am doing wrong? Do I need to enable API access for my account in order for API keys to work?

This is the code I use, from Coinbase github repository for C#
```

string keyName = "here I place the nick name of my API key";
string secret = @"here I place the long secret text generated in final API creation window";
string pass = "here I place passphrase specified before creation of API key";

var authenticator = new Authenticator(keyName, secret, pass);

//create the CoinbasePro client
var coinbaseProClient = new CoinbasePro.CoinbaseProClient(authenticator);

//use one of the services 
var allAccounts = coinbaseProClient.AccountsService.GetAllAccountsAsync().Result;

```

**Comment by dougdellolio** [comment]
hi @oscar54321, the key name you are using may be wrong. Make sure to use the generated key above the the API nickname and not the nickname itself.

**Comment by oscar54321** [comment]
Oh, Doug, thank you so much! I thought that scrambled string was "Default Portfolio" ID, I would have never figured out it is the key. 

PS If I can apple cash you $20, please let me know privately your phone #. :)

**Comment by dougdellolio** [comment]
no worries,  i'm glad it works 😃
