### ISSUE TITLE
AbstractService.SendHttpRequestMessageAsyncWithRetry for paginating requests

### ISSUE THREAD

**Issue by oscar54321** [dougdellolio/coinbasepro-csharp#251]
Hello Guys,

I am trying now and then get a bunch of historical data. Framework itself is trying to throttle requests but it is not doing it comprehensively (for example, GetAllSubsequentPages has delay for paginated series itself, but it is not aware that a few other request might have executed just before and reduced the available quota). This is to propose wrapping up http requests with a simple higher level access method supporting retry for request rate limit violation. RetryAttempts could be also made a class parameter for backward compatibility.

Example code below. What do you think?

```
 private async Task<HttpResponseMessage> SendHttpRequestMessageAsyncWithRetry(
          HttpMethod httpMethod,
          string uri,
          string content = null)
        {
            HttpResponseMessage subsequentHttpResponseMessage = await ExecuteRetry(call);

            async Task<HttpResponseMessage> call()
            {
                return await SendHttpRequestMessageAsync(HttpMethod.Get, uri, content).ConfigureAwait(false);
            }

        }

async Task<HttpResponseMessage> ExecuteRetry(Func<Task<HttpResponseMessage>> func)
        {
            const int MaxRetryAttempts = 3;
            
            int attempt = 0;

            while (true)
            try
            {
                attempt++;
                HttpResponseMessage retval = await func();
                return retval;
            }
            catch (CoinbaseProHttpException err)
            {
                if ((int)err.StatusCode == 429)
                {
                    if (attempt <= MaxRetryAttempts)
                        await Task.Delay(1000);
                    else
                        throw;
                }
                else
                    throw;
           }
        }

```

**Comment by dougdellolio** [comment]
hi @oscar54321, please take a look at overriding the HttpClient behavior https://github.com/dougdellolio/coinbasepro-csharp#overriding-the-httpclient-behavior. I think this will help solve your problem if you're seeing rate limiting issues. You can override the behavior to make the requests as you please. Another thread to read through is here (https://github.com/dougdellolio/coinbasepro-csharp/issues/85) for some examples of how some other users have done it(https://github.com/dougdellolio/coinbasepro-csharp/issues/85#issuecomment-372870936). let me know if this doesn't solve the issue you're describing
