### ISSUE TITLE
Retrieving history of deposits

### ISSUE THREAD

**Issue by ahilis** [dougdellolio/coinbasepro-csharp#254]
Hi
there is a method "List deposits" in coinbase pro api via url "/transfers" : https://docs.pro.coinbase.com/?r=1#list-deposits
ICoinbaseProClient contains the same method for withdrawals but not for deposits.
Was it implemented or missed? Is there another way to get the list deposits?

**Comment by dougdellolio** [comment]
hey @ahilis . I just published this with the next version on Nuget (https://github.com/dougdellolio/coinbasepro-csharp/releases/tag/v1.0.43) Let me know if you see any issues. thanks!

**Comment by ahilis** [comment]
Thanks for such a quick fix!
