### ISSUE TITLE
Withdrawal details contract is not fully implemented

### ISSUE THREAD

**Issue by ahilis** [dougdellolio/coinbasepro-csharp#255]
withdrawals and deposits use the same contract - Transfer which is sufficient for deposits but in case of withdrawals 2 fields are missed:
![image](https://user-images.githubusercontent.com/6560240/103328925-75577c80-4a7c-11eb-979b-63c490a1812c.png)

**Comment by dougdellolio** [comment]
hey @ahilis . added with https://github.com/dougdellolio/coinbasepro-csharp/commit/7abbbb7ab5ae848665d7d42e8af32f53802e758c. this will go out with next release. thanks!

**Comment by ahilis** [comment]
Thanks!
What date of the next release?
