### ISSUE TITLE
Addresses resouce is missed

### ISSUE THREAD

**Issue by ahilis** [dougdellolio/coinbasepro-csharp#258]
It is also seems missed in AccountsService =)
https://developers.coinbase.com/api/v2#addresses

**Comment by ahilis** [comment]
looks like it's been added in v2
cant't clearly understand the workflow, maybe you could give me a hint?
1. how to get btc/eth address to deposits funds directly to Coinbase PRO account? (there is no way currently to get pro's wallet address)
2. how to make deposit properly? deposit CoinbaseAccount first and then DepositCoinbaseFundsAsync to transfer funds to PRO account and be able to place an order?
3. Do Account and CoinbaseAccount have different wallet addresses?

**Comment by dougdellolio** [comment]
hey, this resource is for Coinbase not Coinbase Pro so it wouldn't make sense to add. This library interacts with the exchange (Coinbase Pro) only and not regular Coinbase. 

If you're looking to deposit from Coinbase to Coinbase Pro 
1. Retrieve your Coinbase account ID from CoinbaseAccountsService
2. Use the AccountId from above and pass into DepositCoinbaseFundsAsync (in `DepositsService`) to deposit funds into your Pro account. The docs for this method can be found here: https://docs.pro.coinbase.com/#coinbase

Also, I recommend either testing this on sandbox first or testing with a small amount in case you put in the wrong account ids. I am not sure what the process to recover funds is. Hope this helps
