### ISSUE TITLE
LTC-USDC pair is missed

### ISSUE THREAD

**Issue by ahilis** [dougdellolio/coinbasepro-csharp#259]
hey, its me again)
this pair is missed in ProductType enum
btw, is there any ETA of the next release?

**Comment by dougdellolio** [comment]
hey @ahilis . i don't see LTC-USDC as a valid trading pair so I don't think it makes sense to add.

![image](https://user-images.githubusercontent.com/4141717/104772393-5ece4800-5741-11eb-9cea-4c0bb322dea1.png)

there's no set schedule.  Typically as changes pile up over time, I do releases. 

will close for now, thanks!
