### ISSUE TITLE
Withdrawal details wrong property type

### ISSUE THREAD

**Issue by ahilis** [dougdellolio/coinbasepro-csharp#260]
One more issue has been found)
On requesting list of withdrawals API returns "coinbase_withdrawal_id":"60016cca61a29806ea777fca"
and then code tries to map it to Withdrawal.Transfer.Details. But the property has type Guid => we get exception on json deserialization.
Actually, don't know why, it looks like Guid in docs...
Could you please fix and maybe make a new release?

Also, prop CoinbaseWithdrawalId is useless in Deposits.Transfer.Details

**Comment by dougdellolio** [comment]
hi @ahilis.  the docs do show them as Guid but sometimes the docs are wrong. Changed to a string to be safe and removed the useless prop.  I have released the latest to nuget (https://github.com/dougdellolio/coinbasepro-csharp/releases/tag/v1.0.44), so please update when you can.

thanks
