### ISSUE TITLE
GetProductTickerAsync productType=XrpUsd

### ISSUE THREAD

**Issue by gggustavo** [dougdellolio/coinbasepro-csharp#261]
Hello! 
When Call GetProductTickerAsync with **XrpUsd**
threw exception: CoinbasePro.Exceptions.CoinbaseProHttpException: NotFound

GDAX.Api.ClientLibrary Version=1.0.44
Thanks!

**Comment by dougdellolio** [comment]
hey! @gggustavo. XRP was suspended as of today (January 19, 2021). You can read more about it here: https://blog.coinbase.com/coinbase-will-suspend-trading-in-xrp-on-january-19-2e09652dbf57

![image](https://user-images.githubusercontent.com/4141717/105107217-9e6c9b00-5a85-11eb-892a-4cead5f05c54.png)

**Comment by gggustavo** [comment]
Thanks @dougdellolio
