### ISSUE TITLE
Deposits and withdrawals paging

### ISSUE THREAD

**Issue by ahilis** [dougdellolio/coinbasepro-csharp#262]
Hi,
I've found that paging for the method: DepositSerivce.GetAllDepositsAsync() is not implemented, right?
Filters (before and start) are only works with dates (not time), so in case if account will receive more that 100 deposits, only first 100 will be available from API. But how to get the rest without paging?
Same for WithdrawalsService.GetAllWithdrawals().

**Comment by dougdellolio** [comment]
I believe the way this endpoint works is you request the deposits and withdrawals by passing a date and time stamp with `before` and `after`. I have committed a change that should allow you to use the time component now as the way the format worked before did not allow for it. https://github.com/dougdellolio/coinbasepro-csharp/commit/a981d6dafb108c8e1b23e437ea7b6e3ab282080b. The time you pass in should be in UTC and you can get the deposits/transfers by passing in slices of time. Please refer to the docs for more information on what before and after do - https://docs.pro.coinbase.com/#list-deposit

hope this helps

**Comment by ahilis** [comment]
Yes thank you, the problem is that the package sends dates only.
When the fix will be released?
