### ISSUE TITLE
Please add Unsubscribe to Websocket Feed Channel

### ISSUE THREAD

**Issue by minskowl** [dougdellolio/coinbasepro-csharp#264]
Need to possible usubscribe from separate channel
https://docs.pro.coinbase.com/#subscribe
"If you want to unsubscribe from channel/product pairs, send an unsubscribe message. The structure is equivalent to subscribe messages."

We start trading One instrument 
Subscribe ticker chanel BTC-USD
Than start trading another instrument 
Subscribe ticker chanel GBP-USD

when we finish trading one intrument  we must kept all subscribtions.

**Comment by dougdellolio** [comment]
hey @minskowl. I believe you should be able to do this already using `ChangeChannels(..)` on the Websocket object. https://github.com/dougdellolio/coinbasepro-csharp/blob/master/CoinbasePro/WebSocket/WebSocket.cs#L125

let me know if this doesn't work

**Comment by minskowl** [comment]
Sorry.
Thanks for help
