### ISSUE TITLE
API change for cancelling orders - requires symbol  by 2 weeks after 01/28/2021

### ISSUE THREAD

**Issue by SirOsisOfTheLiver** [dougdellolio/coinbasepro-csharp#266]
from : https://docs.pro.coinbase.com/

Upcoming Changes
01/28/21

API FIX - Order Cancel Request (F) endpoint will require the Symbol field after a two-week lead period. After two weeks, this will be hard-enforced. It is recommended to prepare for this change now.

**Comment by dougdellolio** [comment]
hey @SirOsisOfTheLiver - this change looks like it might be for the FIX API only. It is unclear to me if it will also be hard enforced for the REST API but as of now all seems to work as is. Either way I will keep an eye out and make the updates as necessary. thanks for the heads up

**Comment by SirOsisOfTheLiver** [comment]
OK, thanks
