### ISSUE TITLE
"LINK-USDC" cannot be mapped to the enum type

### ISSUE THREAD

**Issue by lasoares** [dougdellolio/coinbasepro-csharp#270]
ERR The response value "LINK-USDC" cannot be mapped to the enum type "CoinbasePro.Shared.Types.ProductType".

**Comment by dougdellolio** [comment]
@lasoares LINK-USDC is a sandbox only trading pair and is not on the live servers therefore we have chosen not to add it here. I would suggest using a different pair that exists on both sandbox and live servers.
