### ISSUE TITLE
https://docs.pro.coinbase.com/#get-currencies

### ISSUE THREAD

**Issue by ahilis** [dougdellolio/coinbasepro-csharp#271]
Hi
I found one more thing which is quite important and would be nice to have:
https://docs.pro.coinbase.com/#get-currencies
API return a lot of useful information but the package's contract contains only Id, Name and MinSize props

**Comment by dougdellolio** [comment]
hey @ahilis  added this here https://github.com/dougdellolio/coinbasepro-csharp/commit/b03e7af4aa472457ef616a3b4236eefc07ce37f0 and will go out with next release. I've also added the ability to query for single currencies (https://docs.pro.coinbase.com/#get-a-currency). Seems like they just added that endpoint.

thx
