### ISSUE TITLE
Getting Historical Price data

### ISSUE THREAD

**Issue by Markwardtj** [dougdellolio/coinbasepro-csharp#272]
In the CoinbasePro Api there is a get historic rates endpoint.

https://docs.pro.coinbase.com/#get-historic-rates

Is this implemented?

**Comment by dougdellolio** [comment]
hi @Markwardtj , yes this is implemented, please take a look here

https://github.com/dougdellolio/coinbasepro-csharp#products

and here to get started:

https://github.com/dougdellolio/coinbasepro-csharp#how-to-use
