### ISSUE TITLE
Websocket and Authentication

### ISSUE THREAD

**Issue by cmorgado** [dougdellolio/coinbasepro-csharp#275]
Hi reading the documentation I'm doing 
`
 public CoinbaseClient()
        {
        
            var coinbaseProClient = new CoinbaseProClient();
            _websocket = coinbaseProClient.WebSocket;

            _websocket.OnHeartbeatReceived += WebSocketOnOnHeartbeatReceived;
            _websocket.OnTickerReceived += WebSocketOnOnTickerReceived;
        }

        public void AddTicker(ProductType productType)
        {
            _productTypes.Add(productType);
            if (_websocket.State==WebSocketState.Open)
                _websocket.Stop();

            _websocket.Start(_productTypes, new List<ChannelType>() { ChannelType.Full, ChannelType.User });
        }
`

But I get an error on blazor:
 Unhandled exception rendering component: System.Security.Cryptography.X509Certificates is not supported on this platform.
System.PlatformNotSupportedException: System.Security.Cryptography.X509Certificates is not supported on this platform.

Being that I'm using the anonymous socket is there a workaround?

**Comment by dougdellolio** [comment]
hey @cmorgado, just did some digging and found this related to blazor: https://docs.microsoft.com/en-us/dotnet/core/compatibility/cryptography/5.0/cryptography-apis-not-supported-on-blazor-webassembly. Are you seeing any warnings about it? Unfortunately, there doesn't look to be any good workarounds at the moment according to that article

**Comment by cmorgado** [comment]
Hi, I've also been digging on it... and the "culprit" is WebSocket4Net Library. ..
I've been experimenting with the https://docs.microsoft.com/en-us/dotnet/api/system.net.websockets.clientwebsocket?view=net-5.0 ... 
But it's not helpful for you due to be dotnet5 only.

I'm going to see if can remove the WebSocket4Net dependency somehow and use this version for my use case.

My use case is building a Blazor App (webassembly) so I can track my investment in Realtime.

Thank you for your support and great work!
