### ISSUE TITLE
Please add product pairs for ANKR, CVR and STORJ.

### ISSUE THREAD

**Issue by JensKDK** [dougdellolio/coinbasepro-csharp#278]
Please note that STORJ-EUR is not available.

Thank you very much!

**Comment by dougdellolio** [comment]
hey @JensKDK - these have already been added here 😄 : https://github.com/dougdellolio/coinbasepro-csharp/commit/c80810e1e5d71f58f48ddf2fcc3283eb36006eb6

**Comment by JensKDK** [comment]
I'm soooorry 😑
Thanks!
