### ISSUE TITLE
Getting rid of ProductType.

### ISSUE THREAD

**Issue by JensKDK** [dougdellolio/coinbasepro-csharp#279]
Hi,

I've searched issues, and it seems this subject was last discussed i 2018. I know this is a breaking change, but I think there are good reasons to consider it again now. Please bear with me.

1) The primary reason, imo, is missing out on the volatility when new products are activated for trading on the exchange. It would be great to be able to check for new products once an hour, and then use GetSingleProduct every 5 minutes or so, to check status for the products that are not trading yet. If a Product-enum is missing, you can't do this.

2) You need to get GetAllProducts anyways, to check trading status on the Products. Once you have that list, you don't really need the enum anymore. I personally run my trader entirely on the "BTC-EUR" string, and then convert to ProductType when the call to the API is made.

3) When you make the initial GetAllProducts, you have to then check if every product has an enum, and delete the ones who doesn't. Not that big of a deal, but it has to be done.

4) Coinbase is adding new products at a faster pace now. Who knows if this will continue, but more products means more $ for Coinbase, so probably not. Removing ProductType could save you a lot of updates. You are very quick to update, which I appreciate immensely, but without ProductType you wouldn't have to. 

I know it's a lot of work for everyone, but it would make the API more powerful imo. Maybe others can add to the list of arguments, pro or con.

Thank you.

**Comment by dougdellolio** [comment]
hey @JensKDK this has been a topic of discussion for a long time, and you're right -  I think it's time we do this. They have been ramping up adding these new currencies and its not maintainable to have to keep updating our hardcoded list. I have a PR open with this change here that will allow for a string in place of an enum: https://github.com/dougdellolio/coinbasepro-csharp/pull/280. I plan to merge this shortly as I continue my testing. The valid pairs can be obtained from `ProductsService.GetAllProducts()` and will give you the ability to trade any pair as soon as they are available without having to upgrade the package version. 

let me know if you have any additional thoughts - thx!

**Comment by JensKDK** [comment]
Hi @dougdellolio,
I'm so glad you agree. #280 is the way. I have nothing to add.
Thank you very much!
