### ISSUE TITLE
FillsService GetAllFillsAsync doesnt work anymore

### ISSUE THREAD

**Issue by prozerran** [dougdellolio/coinbasepro-csharp#284]
As the title says, now it requires a product_id or order_id.
But the params for input are only limit and no_pages.

**Comment by dougdellolio** [comment]
hey @prozerran. this method was marked obselete a few years ago. I've finally removed it with https://github.com/dougdellolio/coinbasepro-csharp/commit/5af10a807b2ba480676e33541e873e37e316c498. Please use the other methods available to request by `product_id` or `order_id` (https://github.com/dougdellolio/coinbasepro-csharp/blob/master/CoinbasePro/Services/Fills/IFillsService.cs)

thanks!
