### ISSUE TITLE
basic install not working

### ISSUE THREAD

**Issue by DesenEnterprises** [dougdellolio/coinbasepro-csharp#287]
Hey, I downloaded your master solution, added a project and inserted the basic connection:

//create an authenticator with your apiKey, apiSecret and passphrase
            var authenticator = new Authenticator(apiKey, apiSecret, passPhrase); <-- using the keys I just created today

            //create the CoinbasePro client
            var coinbaseProClient = new CoinbasePro.CoinbaseProClient(authenticator);

            //use one of the services 
            var allAccounts = await coinbaseProClient.AccountsService.GetAllAccountsAsync();

I get invalid API key error...

I assume the "secret" is the number that shows up on my Key configuration after I've created it?  Image below:

![image](https://user-images.githubusercontent.com/34489471/117520943-18635a00-af79-11eb-8971-7377b414d1a0.png)

**Comment by dougdellolio** [comment]
hi @DesenEnterprises 

Here are some steps:

1. Navigate to the API section of your profile and press "New API Key"
2. The Passphrase box on this form should be passed into the "passphrase" section of the authenticator
3. Press "Create API Key" and you'll see a dialog that says "API Key Created"
4. The API secret here will be passed into the "apiSecret" section of the authenticator. You only are shown this once so make sure to note it down in a safe place.
5. The text underneath the "cryptoWatch" title in your screenshot would be passed into the "apiKey" section of the authenticator

let me know how this works out

**Comment by DesenEnterprises** [comment]
That was it.

I was using the apiKey for the secret and visa-versa.

I switched them in the call and it works perfectly.

Thank you!


________________________________
