### ISSUE TITLE
Question: Coinbase Prime changing API urls

### ISSUE THREAD

**Issue by henningms** [dougdellolio/coinbasepro-csharp#289]
Hi there,

It might not be a question you can answer, but I've been using this library with ease for my Coinbase Prime account, and I can see that Coinbase Prime do have their own API URL and that will change 3rd of June from api.prime.coinbase.com to api.exchange.coinbase.com.

I'm wondering if you think the change of API url will have any impact seeing that this library target the Coinbase Pro API url which somehow also works with Prime accounts?

If you think it might impact something, what options do we have to support the Prime API url?

Thanks for taking your time to answer :D

**Comment by dougdellolio** [comment]
hey @henningms . thanks for pointing this out. Can't say for sure but if it requires us to use the new URL only to access Prime then this should be easy enough to add in as a feature.  We can add some sort of flag to allow you to switch between Prime and Pro URLs as the APIs seem to be identical. Let's come back to this June 3 and see how it looks.

**Comment by dougdellolio** [comment]
@henningms just following up here. let me know if this requires any work, otherwise we can close this issue

**Comment by henningms** [comment]
It seems to be working just fine for now :) Thanks for following up!
