### ISSUE TITLE
Can this library generate new set of Api Keys?

### ISSUE THREAD

**Issue by TimSharppoint** [dougdellolio/coinbasepro-csharp#295]
As in the title, can the library of Coinbase API it self allows this....

- generate a new set of Api Keys (Secret + Key) , with input parameter PassPhrase and maybe ACL
- get the newly generated Api Keys (by PassPhrase?)
- get a list of currently available and valid Api Keys (Secret + Key + Passphrase)

Not sure if the Coinbase Api support this, but if it does, can your library be updated to support this?

**Comment by dougdellolio** [comment]
hi @TimSharppoint  unfortunately the Coinbase Pro API does not support programmatically generating API keys are far as I am aware. If they ever do support this, I would be happy to add here. 

Thanks
